name: trivia
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/